export const COLORS = {
  background: "#000000",
  card: "#1C1C1E",
  primary: "#32ADE6",
  danger: "#FF453A",
  success: "#34C759",
};

export const ITEMS = {
  LANDMINE: { id: "mine", name: "Landmijn", color: "#FF9500", icon: "bomb" },
  LIGHTNING: { id: "zap", name: "Bliksem", color: "#FFD60A", icon: "zap" },
};

export const BOARD_TILES = [
  {
    id: 1,
    name: "Verwissel plaatsen met iemand",
    icon: "shuffle",
    description: "Kies een speler en wissel van plek",
    sipCount: 0,
    actionType: "modal",
    moveAmount: 0,
  },
  {
    id: 2,
    name: "Neem 1 slok voor elke speler",
    icon: "user",
    description: "Tel iedereen en drink dat aantal slokken",
    sipCount: 0,
    actionType: "self",
    sipsPerPlayer: 1,
    moveAmount: 0,
  },
  {
    id: 3,
    name: "Waterfall",
    icon: "water",
    description:
      "Iedereen begint tegelijk te drinken. Stop pas als de speler voor je stopt. Jij begint.",
    sipCount: 0,
    actionType: "info",
    moveAmount: 0,
  },
  {
    id: 11,
    name: "Drink 2 slokken",
    icon: "beer",
    description: "Simpel maar effectief!",
    sipCount: 2,
    actionType: "self",
    moveAmount: 0,
  },
  {
    id: 12,
    name: "Geef 2 slokken weg",
    icon: "hand-holding",
    description: "Kies iemand die moet drinken",
    sipCount: 2,
    actionType: "give",
    moveAmount: 0,
  },
  {
    id: 13,
    name: "Iedereen ruilt drankje",
    icon: "exchange-alt",
    description: "Ruil van drankje met een andere speler",
    sipCount: 0,
    actionType: "everyone",
    moveAmount: 0,
  },
  {
    id: 14,
    name: "Drink 1 slok als je lacht",
    icon: "smile",
    description: "Iedereen die lacht, drinkt 1 slok",
    sipCount: 1,
    actionType: "everyone",
    moveAmount: 0,
  },
  {
    id: 15,
    name: "Neem 2 stappen vooruit",
    icon: "arrow-right",
    description: "Snel vooruit!",
    sipCount: 0,
    actionType: "modal",
    moveAmount: 2,
  },
  {
    id: 16,
    name: "Neem 2 stappen terug",
    icon: "arrow-left",
    description: "Pas op, terug naar vorige uitdaging",
    sipCount: 0,
    actionType: "modal",
    moveAmount: -2,
  },
  {
    id: 17,
    name: "Maak een gek geluid",
    icon: "volume-up",
    description: "Als niemand lacht, drink 2 slokken",
    sipCount: 2,
    actionType: "modal",
    moveAmount: 0,
  },
  {
    id: 18,
    name: "Probeer iemand te laten lachen",
    icon: "grin-beam",
    description: "Als iemand lacht, drink jij 1 slok",
    sipCount: 1,
    actionType: "self",
    moveAmount: 0,
  },
  {
    id: 19,
    name: "Iedereen zegt een compliment",
    icon: "heart",
    description: "Iedereen die geen compliment geeft, drinkt 1 slok",
    sipCount: 1,
    actionType: "everyone",
    moveAmount: 0,
  },
  {
    id: 20,
    name: "Swap drankjes",
    icon: "sync-alt",
    description: "Ruil van drankje met speler naar keuze",
    sipCount: 0,
    actionType: "modal",
    moveAmount: 0,
  },
  {
    id: 21,
    name: "Neem 1 slok extra als je rood draagt",
    icon: "tshirt",
    description: "Pas op, kleding kan kosten!",
    sipCount: 1,
    actionType: "self",
    moveAmount: 0,
  },
  {
    id: 22,
    name: "Iedereen kiest een slok extra",
    icon: "dice",
    description: "Iedereen rolt dobbelsteen en drinkt het aantal",
    sipCount: 0,
    actionType: "everyone",
    moveAmount: 0,
  },
  {
    id: 23,
    name: "Neem 3 slokken als je linkerhand gebruikt",
    icon: "hand-paper",
    description: "Controleer wie dominant is!",
    sipCount: 3,
    actionType: "self",
    moveAmount: 0,
  },
  {
    id: 24,
    name: "Iedereen wisselt plek met links",
    icon: "arrow-left",
    description: "Een snelle chaotische beweging",
    sipCount: 0,
    actionType: "everyone",
    moveAmount: 0,
  },
  {
    id: 25,
    name: "Vertel een geheim",
    icon: "eye",
    description: "Als je weigert, drink 2 slokken",
    sipCount: 2,
    actionType: "self",
    moveAmount: 0,
  },
  {
    id: 26,
    name: "Doe 5 jumping jacks",
    icon: "running",
    description: "Als je niet doet, drink 2 slokken",
    sipCount: 2,
    actionType: "self",
    moveAmount: 0,
  },
  {
    id: 27,
    name: "Alle mannen drinken 1 slok",
    icon: "mars",
    description: "Mannelijke spelers drinken 1 slok",
    sipCount: 1,
    actionType: "everyone",
    moveAmount: 0,
  },
  {
    id: 28,
    name: "Alle vrouwen drinken 1 slok",
    icon: "venus",
    description: "Vrouwelijke spelers drinken 1 slok",
    sipCount: 1,
    actionType: "everyone",
    moveAmount: 0,
  },
  {
    id: 29,
    name: "Lach om een grap of drink",
    icon: "laugh-beam",
    description: "Als je niet lacht, 2 slokken",
    sipCount: 2,
    actionType: "self",
    moveAmount: 0,
  },
  {
    id: 30,
    name: "Iedereen kiest iemand die 2 slokken drinkt",
    icon: "hand-paper",
    description: "Een sociale uitdaging!",
    sipCount: 2,
    actionType: "everyone",
    moveAmount: 0,
  },
  {
    id: 31,
    name: "Gooi een dobbelsteen: 1-3 drink, 4-6 niets",
    icon: "dice",
    description: "Het lot bepaalt",
    sipCount: 2,
    actionType: "self",
    moveAmount: 0,
  },
  {
    id: 32,
    name: "Iedereen doet een imitatie",
    icon: "mask",
    description: "Wie het slechtst imiteert drinkt 2 slokken",
    sipCount: 2,
    actionType: "everyone",
    moveAmount: 0,
  },
  {
    id: 33,
    name: "Neem 3 stappen vooruit",
    icon: "arrow-right",
    description: "Een snelle boost!",
    sipCount: 0,
    actionType: "modal",
    moveAmount: 3,
  },
  {
    id: 34,
    name: "Neem 3 stappen terug",
    icon: "arrow-left",
    description: "Oeps, verkeerde beurt!",
    sipCount: 0,
    actionType: "modal",
    moveAmount: -3,
  },
  {
    id: 35,
    name: "Drink 2 slokken als je schoenen draagt",
    icon: "shoe-prints",
    description: "Controleer je schoenen!",
    sipCount: 2,
    actionType: "self",
    moveAmount: 0,
  },
  {
    id: 36,
    name: "Iedereen zegt een tongbreker",
    icon: "language",
    description: "Wie faalt, drinkt 2 slokken",
    sipCount: 2,
    actionType: "everyone",
    moveAmount: 0,
  },
  {
    id: 37,
    name: "Iedereen wisselt stoel",
    icon: "chair",
    description: "Een snelle switch",
    sipCount: 0,
    actionType: "everyone",
    moveAmount: 0,
  },
  {
    id: 38,
    name: "Zing een liedje",
    icon: "music",
    description: "Als je weigert, drink 2 slokken",
    sipCount: 2,
    actionType: "self",
    moveAmount: 0,
  },
  {
    id: 39,
    name: "Drink 1 slok voor elke keer dat je 'oké' zegt",
    icon: "comment",
    description: "Tel goed mee!",
    sipCount: 1,
    actionType: "self",
    moveAmount: 0,
  },
  {
    id: 40,
    name: "Kies iemand die een gek gezicht moet trekken",
    icon: "grin",
    description: "Wie lacht, drinkt 1 slok",
    sipCount: 1,
    actionType: "self",
    moveAmount: 0,
  },
  {
    id: 41,
    name: "Doe alsof je een dier bent",
    icon: "paw",
    description: "Wie niet meedoet, drinkt 2 slokken",
    sipCount: 2,
    actionType: "self",
    moveAmount: 0,
  },
  {
    id: 42,
    name: "Iedereen zegt een compliment",
    icon: "heart",
    description: "Wees aardig of drink!",
    sipCount: 2,
    actionType: "everyone",
    moveAmount: 0,
  },
  {
    id: 43,
    name: "Kies iemand die 3 slokken drinkt",
    icon: "hand-holding",
    description: "Geef het door!",
    sipCount: 3,
    actionType: "give",
    moveAmount: 0,
  },
  {
    id: 44,
    name: "Iedereen doet een challenge",
    icon: "trophy",
    description: "Wie verliest, drinkt 2 slokken",
    sipCount: 2,
    actionType: "everyone",
    moveAmount: 0,
  },
  {
    id: 45,
    name: "Spring op één been 5 keer",
    icon: "running",
    description: "Wie faalt, drinkt 2 slokken",
    sipCount: 2,
    actionType: "self",
    moveAmount: 0,
  },
  {
    id: 46,
    name: "Neem een selfie met iemand",
    icon: "camera",
    description: "Weigeren = 2 slokken",
    sipCount: 2,
    actionType: "self",
    moveAmount: 0,
  },
  {
    id: 47,
    name: "Doe een dansbattle",
    icon: "dance",
    description: "Verliezer drinkt 2 slokken",
    sipCount: 2,
    actionType: "everyone",
    moveAmount: 0,
  },
  {
    id: 48,
    name: "Iedereen noemt een dier",
    icon: "paw",
    description: "Wie het niet kan, drinkt 2 slokken",
    sipCount: 2,
    actionType: "everyone",
    moveAmount: 0,
  },
  {
    id: 49,
    name: "Drink 2 slokken als je horloge draagt",
    icon: "clock",
    description: "Pas op, accessoires tellen!",
    sipCount: 2,
    actionType: "self",
    moveAmount: 0,
  },
  {
    id: 50,
    name: "Iedereen doet een pirouette",
    icon: "sync-alt",
    description: "Wie valt, drinkt 2 slokken",
    sipCount: 2,
    actionType: "everyone",
    moveAmount: 0,
  },
  {
    id: 51,
    name: "Kies iemand die 1 slok extra drinkt",
    icon: "hand-paper",
    description: "Kleine sabotage!",
    sipCount: 1,
    actionType: "give",
    moveAmount: 0,
  },
  {
    id: 52,
    name: "Neem 1 stap vooruit",
    icon: "arrow-right",
    description: "Kleine beweging vooruit",
    sipCount: 0,
    actionType: "modal",
    moveAmount: 1,
  },
  {
    id: 53,
    name: "Neem 1 stap terug",
    icon: "arrow-left",
    description: "Kleine terugslag",
    sipCount: 0,
    actionType: "modal",
    moveAmount: -1,
  },
  {
    id: 54,
    name: "Iedereen drinkt 1 slok",
    icon: "beer",
    description: "Een universele toast!",
    sipCount: 1,
    actionType: "everyone",
    moveAmount: 0,
  },
  {
    id: 55,
    name: "Zeg iets grappigs",
    icon: "laugh",
    description: "Wie lacht, drinkt 1 slok",
    sipCount: 1,
    actionType: "everyone",
    moveAmount: 0,
  },
  {
    id: 56,
    name: "Kies een spelregel voor de volgende ronde",
    icon: "cog",
    description: "Iedereen volgt of drinkt 2 slokken",
    sipCount: 2,
    actionType: "everyone",
    moveAmount: 0,
  },
  {
    id: 57,
    name: "Doe alsof je slaapt",
    icon: "bed",
    description: "Wie beweegt, drinkt 2 slokken",
    sipCount: 2,
    actionType: "everyone",
    moveAmount: 0,
  },
  {
    id: 58,
    name: "Iedereen pakt een item",
    icon: "gift",
    description: "Pak een kaart of drink 1 slok",
    sipCount: 1,
    actionType: "everyone",
    moveAmount: 0,
  },
  {
    id: 59,
    name: "Gooi een dobbelsteen en beweeg dat aantal stappen",
    icon: "dice",
    description: "Laat het lot beslissen",
    sipCount: 0,
    actionType: "self",
    moveAmount: 0,
  },
  {
    id: 60,
    name: "Iedereen drinkt 2 slokken",
    icon: "beer",
    description: "Gezamenlijk plezier!",
    sipCount: 2,
    actionType: "everyone",
    moveAmount: 0,
  },
];
